platform :tvos, '10.0'
use_frameworks!

plugin 'cocoapods-binary'
all_binary!

target 'YouiKalturaPlayerBridgetvOS' do
  
  pod 'KalturaPlayer/OTT', :git => 'https://github.com/kaltura/kaltura-player-ios', :branch => 'develop'

  pod 'PlayKit_IMA'
  pod 'PlayKitYoubora'


### Embedded in KalturaPlayer/OTT - not needed for the release, only when working on a branch ###

  pod 'PlayKit', :git => 'https://github.com/kaltura/playkit-ios', :branch => 'develop'
  #pod 'PlayKitKava', :git => 'https://github.com/kaltura/playkit-ios-kava', :branch => 'develop'
  pod 'PlayKitProviders', :git => 'https://github.com/kaltura/playkit-ios-providers', :branch => 'develop' 


### Embedded in PlayKit - not needed for the release, only when working on a branch ###

  #pod 'PlayKitUtils', :git => 'https://github.com/kaltura/playkit-ios-utils', :branch => 'develop'

end
